### ISSUE TITLE
LightGBM/Xgboost c++ example? 

### ISSUE THREAD

**Issue by skaae** [oneapi-src/oneDAL#1530] opened 2021-03-26 20:08 UTC
Daal4py has an example on converting lightgbm and xgboost models to python and use them for inference.

Is the same possible for C++? Using python to train a model and doing inference in c++?

**Comment by ShvetsKS** [comment] 2021-03-30 06:00
Yes it's possible.
Trained daal4py model (or obtained after conversion from XGBoost/LGBM) can be serialized into binary file via native API:
```
def native_serialization(result, file='native_result.txt'):
    daal_buff = result.__getstate__()
    File = open(file, "wb")
    File.write(daal_buff)
```
...
```
# serialize converted model
daal_model = d4p.get_gbt_model_from_xgboost(xgb_model)
native_serialization(daal_model)
```
or
```
# serialize daal4py trained model
train_algo = d4p.gbt_classification_training(...)
train_result = train_algo.compute(data, labels)
native_serialization(train_result.model)
```

Then in C++ application you should read saved `'native_result.txt'` file and pass byte buffer for deserialization:
```
    /* Deserialization */
    size_t size = 0;
    byte * buffer = read_native_result(size);

    /* the result buffer is now loaded in the buffer. */

    /* Create a data archive to deserialize the numeric table */
    OutputDataArchive out_dataArch(buffer, size);
    free (buffer);

    /* Create an empty algorithm to train the gradient boosted trees classification model */
    daal::algorithms::gbt::classification::training::Batch<> algorithm(nClasses);

    /*Allocate memory for deserialized model */
    algorithm.input.set(classifier::training::data, trainData);
    algorithm.getResult()->allocate<>(algorithm.getInput(),&(algorithm.parameter()),0);
    /* deserialize the Model */
    algorithm.getResult()->get(classifier::training::model)->deserialize(out_dataArch);

 ```

And finally it's possible to perform inference stage on deserialized model:
```
    daal::algorithms::gbt::classification::training::ResultPtr trainingResult = algorithm.getResult();
    /* Create an algorithm object to predict values of gradient boosted trees classification */
    daal::algorithms::gbt::classification::prediction::Batch<> algorithm(nClasses);

    /* Pass a testing data set and the deserialized/trained model to the algorithm */
    algorithm.input.set(classifier::prediction::data, testData);
    algorithm.input.set(classifier::prediction::model, trainingResult->get(classifier::training::model));

    /* Predict values of gradient boosted trees classification */
    algorithm.compute();
```

Is it applicable for your case? If no, please describe your scenario in more details.

**Comment by ShvetsKS** [comment] 2021-03-30 06:50
Implementation of `read_native_result` function.
```cpp

byte* read_native_result(size_t& size)
{
    byte * buffer = NULL;
    FILE * pFile;
    size_t result;

    pFile = fopen ( ".native_result.txt" , "rb" );
    if (pFile==NULL)
    {
        fputs ("File error",stderr);
        exit (1);
    }

    // obtain file size:
    fseek (pFile , 0 , SEEK_END);
    size = ftell (pFile);
    std::cout << "size: " << size << "\n";
    rewind(pFile);

    // allocate memory to contain the whole file:
    buffer = (byte*) malloc (sizeof(byte)*size);
    if (buffer == NULL)
    {
        fputs ("Memory error",stderr);
        exit (2);
    }

    // copy the file into the buffer:
    result = fread (buffer,1,size,pFile);
    if (result != size)
    {
        fputs ("Reading error",stderr);
        exit (3);
    }
    fclose (pFile);
    return buffer;
}
```

**Comment by skaae** [comment] 2021-04-01 10:17
Thats awesome thanks :).

**Comment by SmirnovEgorRu** [comment] 2021-04-13 21:08
@skaae, does the solution cover your scenario? :)
Can we close the task in this case?

**Comment by ykerit** [comment] 2021-06-30 14:38
@SmirnovEgorRu 
I have the same problem, I ran the gbt regression model with the code commented above, then I ran it twice with the same input and got different results.
```
void load_data(NumericTablePtr& test_data) {
    HomogenNumericTable<float> table(27, 1, NumericTable::doAllocate, 0.0);
    test_data = HomogenNumericTable<>::create(data, 27, 2);
}

void test_model() {
    NumericTablePtr testData;
    load_data(testData);

    prediction::Batch<> algorithm;

    auto model_path = "daal_xgboost_model.txt";
    std::ifstream file(model_path, std::ios::in|std::ios::binary|std::ios::ate);
    if(!file) {
        std::cout << "loading model error" <<std::endl;
        assert(false);
    }
    size_t length = file.tellg();
    file.seekg(0, std::ios::beg);
    byte* buffer = new byte[length];
    file.read((char*)buffer, length);
    file.close();

    OutputDataArchive out_dataArch(buffer, length);
    delete[] buffer;
    daal::algorithms::gbt::regression::ModelPtr deserialized_model = daal::algorithms::gbt::regression::Model::create(27);
    deserialized_model->deserialize(out_dataArch);
    std::cout << deserialized_model->numberOfTrees() << std::endl;
    std::cout << deserialized_model->getNumberOfFeatures() << std::endl;

    algorithm.input.set(prediction::data, testData);
    algorithm.input.set(prediction::model, deserialized_model);

    algorithm.compute();

    prediction::ResultPtr predictionResult = algorithm.getResult();
    printNumericTable(predictionResult->get(prediction::prediction), "Gragient boosted trees prediction results (first 10 rows):", 10);
}
```
result output
```
➜  latest ./test_model
201
27
Gragient boosted trees prediction results (first 10 rows):
-0.418
-0.444

➜  latest ./test_model
201
27
Gragient boosted trees prediction results (first 10 rows):
-0.418
-0.418
```

**Comment by ykerit** [comment] 2021-06-30 14:47
This model can get the correct result on python when use pickle to load model

**Comment by SmirnovEgorRu** [comment] 2021-06-30 15:00
@ShvetsKS, please, take a look

**Comment by ShvetsKS** [comment] 2021-06-30 15:15
@ykerit could you check whether this issue is reproduced with prediction algorithm type specification:
 `prediction::Batch<> algorithm;` -> `prediction::Batch<double> algorithm;`.
It's possibly the reason why we can't see the problem with python interfaces.

And it would be good to have some minimum files to reproduce the problem: saved model (or just python script to obtain similar model), two lines from datasets  `data`.

**Comment by ykerit** [comment] 2021-07-01 04:55
thanks! this my test case repo that can reproduce the problem.
https://github.com/ykerit/daal_case

**Comment by ShvetsKS** [comment] 2021-07-01 12:35
@ykerit the exact root cause of this problem is in `load_data` function.
```
void load_data(NumericTablePtr& test_data) {
    float data[27 * 2] = {1.0};
    test_data = HomogenNumericTable<>::create(data, 27, 2);
}
```

Here HomogenNumeric table doesn't do the copy of `data`. And during `prediction` pointer `data` is no longer valid as `data` 'lifetime' was already finished.
If you move allocation into `main` function, results will be equal from run to run.

Also it's possible to use 	`test_data = HomogenNumericTable<float>::create(27, 2, NumericTable::doAllocate, 1.0);` inside load_data to avoid the destruction of input array.

**Comment by ykerit** [comment] 2021-07-01 12:48
Thanks！I mistakenly thought this was a deep copy. Why did the python script fail to load the model？

**Comment by ShvetsKS** [comment] 2021-07-01 13:01
please try to use these functions:
```
def native_deserialization(file='native_result.txt'):
    daal_model = d4p.gbt_regression_model()
    File = open(file, "rb")
    daal_buff = File.read()
    daal_model.__setstate__(daal_buff)
    return daal_model

```
then provide it as a model
`model = native_deserialization("native_result.txt")`
`result = d4p.gbt_regression_prediction().compute(data, model)`

and  for deserialization:

```
def native_serialization(model, file='native_result.txt'):
    daal_buff = model.__getstate__()
    File = open(file, "wb")
    File.write(daal_buff)
...
native_serialization(gbt_reg_alg.daal_model_)

```


Also serialization and deserialization is available via pickle (for python only ):

```
# serialized model can be used only by daal4py with pickle
def pickle_serialization(model, file='df_result.pkl'):
    with open(file,'wb') as out:
        pickle.dump(model, out)

```

```
#returns model
def pickle_deserialization(file='df_result.pkl'):
    with open(file,'rb') as inp:
        return pickle.load(inp)

```

**Comment by ykerit** [comment] 2021-07-01 13:35
I changed the C++ code, the input shape is 27 * 2 and the content is the same, the two output numbers should also be the same, but they are not now. Python script can get consistent results

**Comment by ykerit** [comment] 2021-07-01 13:37
c++ result
```
 Gragient boosted trees prediction results (first 10 rows):
-0.899                                                                                  
-0.872
```
python result:
```
➜  model python3 test.py
prediction: array(
  [[0.48472647]
   [0.48472647]],
  dtype=float64, shape=(2, 1))
```

**Comment by ShvetsKS** [comment] 2021-07-01 13:40
if you are using  `float data[27 * 2] = {1.0};` initialization, there is no guarantee that all elements are set to 1. Please use `std::fill` for it!

**Comment by ykerit** [comment] 2021-07-01 13:51
Thanks a lot！it's awesome！I think these codes can be added to the repo example, guide us in using oneDAL for inference.

**Comment by ShvetsKS** [comment] 2021-07-01 14:46
it's specific case to traine in python and predict in c++, not corresponding format for this repo.
But you can find all python examples here: https://github.com/intel/scikit-learn-intelex/tree/master/examples/daal4py

we will think about how to prepare demo for this specific case, thanks for proposal!

@ykerit  in case all points were resolved, can we close this issue?

**Comment by ykerit** [comment] 2021-07-01 14:50
Can be closed，thanks again！

**Closed** 2021-07-01 16:39 UTC
